# Generated by Django 5.2.10 on 2026-02-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(help_text='Unique identifier for the page', max_length=100, unique=True)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField(max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='A1isherDev', max_length=200)),
                ('hero_title', models.CharField(default="I'm Alisher", max_length=500)),
                ('hero_subtitle', models.CharField(default='Web Developer', max_length=500)),
                ('contact_email', models.EmailField(default='alisher@example.com', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='core/')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(choices=[('discord', 'Discord'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('youtube', 'YouTube')], max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='Font Awesome icon class', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
    ]
