# Generated by Django 5.2.10 on 2026-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_description',
            field=models.TextField(default="I'm a passionate Software Developer who enjoys understanding how systems work."),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_greeting',
            field=models.CharField(default='👋 Hello there!', max_length=100),
        ),
    ]
