# Generated by Django 5.2.10 on 2026-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_hero_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='og_image',
            field=models.FileField(blank=True, null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='core/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='core/'),
        ),
    ]
