# Generated by Django 5.2.10 on 2026-02-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_seo_og_image_alter_sitesetting_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
