# Generated by Django 5.2.10 on 2026-06-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesetting_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('emailed', models.BooleanField(default=False, help_text='Whether a notification email was sent')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='location',
            field=models.CharField(blank=True, default='Remote · Worldwide', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Optional public phone number', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(default='hello@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_description',
            field=models.TextField(default='I build clean, scalable web applications with a focus on great user experiences and reliable backend systems.'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_greeting',
            field=models.CharField(default='👋 Hello, I am', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.CharField(default='Full-Stack Developer', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default="I'm Alex Morgan", max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Alex Morgan', max_length=200),
        ),
    ]
