# Generated by Django 5.2.10 on 2026-02-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=200)),
                ('content', models.TextField()),
                ('greeting', models.CharField(default='👋 Hello there!', max_length=100)),
                ('hero_description', models.TextField()),
                ('education', models.CharField(default='Computer Science', max_length=200)),
                ('location', models.CharField(default='Uzbekistan Fergana', max_length=200)),
                ('years_experience', models.CharField(default='2+', max_length=50)),
                ('projects_completed', models.CharField(default='30+', max_length=50)),
                ('happy_clients', models.CharField(default='0+', max_length=50)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=50, help_text='Skill level from 1 to 100')),
                ('group', models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('database', 'Database Management'), ('devops', 'DevOps & Tools'), ('other', 'Other')], default='other', max_length=20)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['group', 'order', 'name'],
            },
        ),
    ]
