# Generated by Django 5.2.10 on 2026-02-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_service_servicefeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='greeting',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='hero_description',
        ),
    ]
