# Generated by Django 5.2.10 on 2026-06-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_aboutsection_greeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='languages',
            field=models.CharField(blank=True, default='English', help_text='Comma-separated languages you speak', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='happy_clients',
            field=models.CharField(default='10+', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='location',
            field=models.CharField(default='Remote · Worldwide', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='projects_completed',
            field=models.CharField(default='20+', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='years_experience',
            field=models.CharField(default='3+', max_length=50),
        ),
    ]
