# Generated by Django 5.2.10 on 2026-02-20 06:52 (manually edited to add data migration)

from django.db import migrations, models
from django.utils.text import slugify


def populate_technology_slugs(apps, schema_editor):
    """Populate slugs for existing Technology records before adding unique constraint."""
    Technology = apps.get_model('portfolio', 'Technology')
    for tech in Technology.objects.all():
        if not tech.slug:
            tech.slug = slugify(tech.name)
            tech.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        # Step 1: Add slug field WITHOUT unique constraint first
        migrations.AddField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, default=''),
            preserve_default=False,
        ),
        # Step 2: Populate slugs from names for existing rows
        migrations.RunPython(populate_technology_slugs, migrations.RunPython.noop),
        # Step 3: Now add unique constraint
        migrations.AlterField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        # Step 4: Make project image optional
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
